rules:
- name: spot
  checkItems:
  - RunningOnDifferentNodes
  - WithGracefulTermination
  - WithHealthCheck
  - WithResourceRequestAndLimit
- name: deployment
  checkItems:
  - DWithGracefulTermination
  - DWithLiveness
  - DWithResourceRequestAndLimit
  - DWithReadiness
  - WithRollingUpdate
  - DWithEmptyDirSizeLimit
  - DWithTerminationGrace
- name: statefulSet
  checkItems:
  - SWithGracefulTermination
  - SWithLiveness
  - SWithResourceRequestAndLimit
  - SWithReadiness
  - SWithLivenessReadinessDelayCheck
  - SWithEmptyDirSizeLimit
  - SWithTerminationGrace